version: '3.9'

services:
  web:
    build: ./pointsapp
    ports:
      - "80:80"  # Map container's port 80 to host port 80
    networks:
      - web
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5431:5431"
    networks:
      - database
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  web:  # Define the 'web' network
  database:  # Define the 'database' network

volumes:  # Declare the named volume
  postgres_data:  # Name of the volume
