apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-borisvanleuven
  namespace: exam-nginx
  labels:
    app: nginx-borisvanleuven
    kubernetes-label: exam-containers-orchestration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-borisvanleuven
  template:
    metadata:
      labels:
        app: nginx-borisvanleuven
        kubernetes-label: exam-containers-orchestration
    spec:
      containers:
        - name: nginx-container
          image: nathansegers/vue-docker:v2.0.0
          ports:
            - containerPort: 80
